# Basic
title: LiXueLong
subtitle: åˆ«è®©ç­‰å¾…æˆä¸ºé—æ†¾ï¼
# welcome_message: ^_^
description: è¿™æ˜¯æˆ‘ç”¨æ¥è®°å½•å¹³æ—¥å­¦ä¹ ç¬”è®°çš„åœ°æ–¹ï¼Œæ¬¢è¿æ‚¨çš„è®¿é—®.
creator: <a href="http://SkylarkLi.github.io">@xuelong</a>
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
# avatarTitle: LiXueLong
# å¤´åƒé‡Œé¢çš„æè¿°
# avatarDesc: Androidå°ç™½
url: "http://SkylarkLi.github.io"

# Comment
comment:
    # è¯„è®ºç³»ç»Ÿå¥½åƒéƒ½æŒ‚äº†ã€‚ã€‚ã€‚
    # disqus: xuelongli
    # duoshuo:
    # cloudTie: 
# Social
social:
    # weibo: Xuelong_li
    github: skylarklxlong
    zhihu: xuelong-li
    # twitter: 
    # gplus: 
    weibo: 5069128618
    weixing: 898309569 
    mail: li_xuelong@126.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
#baidu:
#    id: 39779e689b1502cc897a73c00bef24ed  

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
#    id: UA-103576063-1   
#    host: auto  
    

# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/SkylarkLi/SkylarkLi.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ
    description: è®¿é—®åšå®¢

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: æ‰€æœ‰æ–‡ç« , url: '/archive'}
    - {title: æ ‡ç­¾, description: æ ‡ç­¾, url: '/tags'}
    - {title: å…³äºæˆ‘, description: äº†è§£æ›´å¤šå…³äºæˆ‘, url: '/about'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"



theme: jekyll-theme-cayman